### ISSUE TITLE
Vuforia v13.1.3

### ISSUE THREAD

**Issue by jpsarda** [PTCInc/vuforia-engine#194]
I'm looking for Vuforia Unity package v13.1.3, please help.

**Comment by ptc-emaggio** [comment]
Hi @jpsarda thanks for filing the issue. As common practice we do not distribute older Vuforia Engine artifacts.

**Comment by jpsarda** [comment]
I can't use Unity 6 because I'm using Unity with Flutter, and the flutter plugin is not supporting Unity 6. I'm stuck, please help.

**Comment by ptc-emaggio** [comment]
Although not recommended the current 11.3 should still work with Unity 2022.3

**Comment by jpsarda** [comment]
Thx, after importing the package com.ptc.vuforia.engine-11.3.4.tgz in Unity 2022, we get this compilation error in one of the .cs files of the package.

![Image](https://github.com/user-attachments/assets/069ede97-b21c-4386-b26b-d9c2928e5240)

**Comment by ptc-emaggio** [comment]
> Thx, after importing the package com.ptc.vuforia.engine-11.3.4.tgz in Unity 2022, we get this compilation error in one of the .cs files of the package.
> 
> ![Image](https://github.com/user-attachments/assets/069ede97-b21c-4386-b26b-d9c2928e5240)

you might have to upgrade ARFoundation as well

**Comment by jpsarda** [comment]
I think AR Foundation 6.0 is compatible with Unity 2023.2 and newer versions and I'm not sure how to install it with Unity 2022 to test it, I'm afraid that would bring a lot of problems. 

I saw in the Vuforia package .cs files that there are a lot of conditions `#if UNITY_XR_ARFOUNDATION` , do you know if there is a way to force this condition to be `false` (even if AR Foundation is installed in the project) ?
I guess that if I uninstall AR Foundation from project, Vuforia should be OK ? We don't really need AR Foundation for our Vuforia use (at least I suppose as we're initializing it with FusionProviderOption.VUFORIA_FUSION_ONLY option), but we use AR Foundation for another part of the app.

![Image](https://github.com/user-attachments/assets/b59a8c26-aab7-40f5-ad12-54767732b64c)

**Comment by jpsarda** [comment]
I managed to make it compile by replacing all occurences of UNITY_XR_ARFOUNDATION by UNITY_XR_ARFOUNDATION_XXX, but still when building the project, Vuforia requires ARCore 6.1, so I'm stuck, and I think I'll stop here. We'll use the `com.ptc.vuforia.engine-10.14.4.tgz` we had archived.
